plugins:
  - remark-preset-lint-recommended
  - remark-lint-code
  - remark-lint-no-repeat-punctuation
  - remark-lint-heading-whitespace
  - remark-preset-lint-markdown-style-guide
settings:
  verbose: true
  quote: "'"
  quoteSmart: true
  preferUnquoted: true
  