version: "3.7"

services:
  jekyll:
    image: swedbankpay/jekyll-plantuml:2.0.1
    command: serve
    container_name: jekyll
    ports:
      - 4000:4000
      - 35729:35729
    volumes:
      - .:/srv/jekyll
      - .bundle:/usr/local/bundle
