version: '3.7'

services:
  jekyll:
    build:
      context: .
      cache_from:
        - ruby:2.7.1
      dockerfile: .docker/Dockerfile
    container_name: jekyll
    ports:
      - 4000:4000
      - 35729:35729
    volumes:
      - .:/srv/jekyll
      - .bundle:/usr/local/bundle
