name: Build and push to gh_pages

on:
  push:
    branches:
    - master

jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v1
        with:
          java-version: '1.8'
      - uses: kamiazya/setup-graphviz@v1
      - name: Installs libfontconfig
        run: sudo apt-get install -y libfontconfig
      - uses: SwedbankPay/jekyll-builder-for-github-pages-action@master
        with:
          secret_gh_pages_api_token: ${{ secrets.GH_PAGES_TOKEN }}
          git_committer_email: dev@payex.com
          git_committer_name: payex-dev
          gh_pages_publishing_source: gh-pages
        env:
          GITHUB_ACTOR: payex-dev
          JEKYLL_GITHUB_TOKEN : ${{ secrets.GH_PAGES_TOKEN }}
          JEKYLL_ENV: production
