
name: Deploy

on:
  push:
    branches:
      - master

jobs:
  variables:
    runs-on: ubuntu-latest
    outputs:
      branch: ${{ steps.variables.outputs.branch }}
      repository_url: ${{ steps.variables.outputs.repository_url }}

    steps:
      - uses: actions/checkout@v2.3.4
      - name: Generate variables
        id: variables
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: .github/scripts/variables.sh

  deploy:
    runs-on: ubuntu-latest
    needs: variables
    steps:
      - uses: actions/checkout@v2.3.4
      - name: Deploy to GitHub Pages
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GITHUB_ACTOR: payex-dev
          GITHUB_ACTOR_EMAIL: dev@payex.com
          GITHUB_REPO: https://${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}.git
        run: |
          docker-compose run \
            -e GITHUB_REPOSITORY_URL=${{ needs.variables.outputs.repository_url }} \
            jekyll deploy \
            --env=production
