name: Docker build site and publish

on: [push, pull_request]

jobs:
  build:
    name: Docker build site and publish
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Docker compose up for CI
      env:
        GITHUB_ACTOR: payex-dev
        GITHUB_ACTOR_EMAIL: dev@payex.com
        GH_PAGES_BRANCH: gh-pages
        GITHUB_TOKEN : ${{ secrets.GITHUB_TOKEN }}
        JEKYLL_ENV: production
      run: |
        docker-compose \
          -f docker-compose.yml \
          -f .docker/docker-compose.ci.yml \
          up --build -d
