name: Docker Compose up works as expected

on: [push, pull_request]

jobs:
  test:
    name: Docker Compose up works as expected
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Docker compose up
      run: |
        docker-compose \
          -f docker-compose.yml \
          -f .docker/docker-compose.ci.yml \
          up -d
      env:
        GITHUB_ACTOR: payex-dev
        JEKYLL_GITHUB_TOKEN : ${{ secrets.GH_PAGES_TOKEN }}
        JEKYLL_ENV: production
        secret_gh_pages_api_token: ${{ secrets.GH_PAGES_TOKEN }}
        git_committer_email: dev@payex.com
        git_committer_name: payex-dev
        gh_pages_publishing_source: gh-pages
