name: Jekyll site CI

on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Docker compose build
      run: |
        docker-compose build -f ./docker-compose.yml
    - name: Docker compose up
      run: |
        docker-compose up -f ./docker-compose.yml
