name: Jekyll build works

on: [push, pull_request]

jobs:
  test:
    name: Jekyll build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v1
        with:
          java-version: '1.8'
      - uses: kamiazya/setup-graphviz@v1
      - name: Installs libfontconfig
        run: sudo apt-get install -y libfontconfig
      - uses: actions/setup-ruby@v1
        with:
          ruby-version: '2.6'
      - name: Install bundle
        run: |
          sudo apt-get -yqq install libpq-dev
          gem install bundler
      - name: Bundle install
        run: |
          bundle install --jobs 4 --retry 3
      - name: Run build
        run: bundle exec jekyll build
      - name: Check for plantUml
        run: |
          grep './_site/index.html' -e 'PlantUML version 1.2020.05'
      - name: Check for material icon
        run: |
          grep './_site/index.html' -e '<i class="material-icons">check</i>'