name: Jekyll site CI

on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Docker run
      run: |
        docker run --rm \
        --volume="${PWD}:/srv/jekyll" \
        jekyll/jekyll:3.8 jekyll build
    - name: Docker compose build
      run: |
        docker-compose \
          -f docker-compose.yml \
          -f docker-compose.ci.yml \
          build
    - name: Docker compose up
      run: |
        docker-compose \
          -f docker-compose.yml \
          -f docker-compose.ci.yml \
          up -d
