name: Jekyll site CI

on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Docker compose build
      run: |
        docker build
    - name: Docker compose up
      run: |
        docker run
