name: Jekyll site CI

on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Docker compose build
      run: |
        docker-compose build -f ./docker-compose.yml -f ./docker-compose.ci.yml