name: Jekyll site CI

on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Docker compose build
      run: |
        docker run \
        --volume="${pwd}:/home/jekyll" \
        --volume="${pwd}/.bundle-cache:/usr/local/bundle" \
        jekyll/minimal:3.8 jekyll build