name: Test

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: jekyll build
      run: |
        docker-compose \
          -f docker-compose.yml \
          -f .docker/docker-compose.build.yml \
          up \
          --abort-on-container-exit \
          --exit-code-from jekyll

  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: rake test
      run: |
        docker-compose \
          -f docker-compose.yml \
          -f .docker/docker-compose.test.yml \
          up \
          --build \
          --abort-on-container-exit \
          --exit-code-from jekyll
