name: Test

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: jekyll build
        run: |
          docker-compose run \
            -e PAGES_REPO_NWO=${{ github.repository }} \
            -e JEKYLL_GITHUB_TOKEN=${{ secrets.GITHUB_TOKEN }} \
            jekyll build
      - name: Upload site
        uses: actions/upload-artifact@v2
        with:
          name: build-site
          path: _site

  spec:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-ruby@v1
        with:
          ruby-version: '2.7'

      - uses: actions/setup-java@v1
        with:
          java-version: '1.8'

      - uses: kamiazya/setup-graphviz@v1

      - name: bundle install
        run: bundle install --jobs 4 --retry 3

      - name: rspec
        env:
          PAGES_REPO_NWO: ${{ github.repository }}
          JEKYLL_GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: bundle exec rake

      - name: codecov upload
        run: bundle exec rake codecov:upload || echo 'Codecov upload failed'

      - name: rubocop
        run: bundle exec rubocop --fail-level warning --display-only-fail-level-offenses

  verify:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Verify build
        run: |
          docker-compose run \
            -e PAGES_REPO_NWO=${{ github.repository }} \
            -e JEKYLL_GITHUB_TOKEN=${{ secrets.GITHUB_TOKEN }} \
            jekyll build \
            --env=production \
            --verify \
            --ignore-url http://www.wikipedia.org \
            --ignore-url http://restcookbook.com/Basics/loggingin/ \
            --ignore-url '%r{/swedbank-pay-design-guide-jekyll-theme/.*}'

      - name: Upload build output artifacts
        uses: actions/upload-artifact@v2
        if: always()
        with:
          name: verify-site
          path: _site

      - name: Verify absolute URL
        run: grep 'https://swedbankpay.github.io/swedbank-pay-design-guide-jekyll-theme/' $(pwd)/_site/index.html

      - name: Verify base URL
        run: grep '/swedbank-pay-design-guide-jekyll-theme/assets/' $(pwd)/_site/index.html

  remark-lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: npm install
      - uses: prologic/action-remark-lint@v0.0.5
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          reporter: github-pr-check

  deploy-dry-run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: deploy dry-run
        run: |
          docker-compose run \
            -e PAGES_REPO_NWO=${{ github.repository }} \
            -e JEKYLL_GITHUB_TOKEN=${{ secrets.GITHUB_TOKEN }} \
            jekyll deploy \
            --env=production \
            --dry-run
      - name: Upload deploy
        uses: actions/upload-artifact@v2
        if: always()
        with:
          name: deploy
          path: .
