name: Test

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: jekyll build
        run: docker-compose run jekyll build

  verify:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: verify
        run: docker-compose run jekyll build --verify

  remark-lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: prologic/action-remark-lint@v0.0.5
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          reporter: github-pr-review

  deploy-dry-run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: deploy dry-run
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GITHUB_ACTOR: payex-dev
          GITHUB_ACTOR_EMAIL: dev@payex.com
          GITHUB_REPO: https://${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}.git
        run: docker-compose run jekyll deploy --dry-run
