name: Verify build output

on: [push, pull_request]

jobs:
  test:
    name: Jekyll output
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Docker compose up
      run: |
        docker-compose \
          -f docker-compose.yml \
          -f .docker/docker-compose.test.yml \
          up