name: Windows workflow

on: [push]

jobs:
  test:
    name: Docker Compose up works as expected
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2

    - name: Docker compose up
      run: docker-compose up -d --build